<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageVersion Include="FluentIcons.Avalonia" Version="2.1.331" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="1.1.1" />
    <PackageVersion Include="NSwag.MSBuild" Version="14.7.1" />
    <PackageVersion Include="ProDataGrid" Version="12.0.4" />
  </ItemGroup>
</Project>
