//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace CodexGui.AppServer.Models
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InitializeResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("userAgent")]
        public string UserAgent { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AccountReadResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("account")]
        public AccountInfo Account { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("requiresOpenaiAuth")]
        public bool RequiresOpenaiAuth { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AccountInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("planType")]
        public string PlanType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RateLimitsReadResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("rateLimits")]
        public RateLimitBucket RateLimits { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rateLimitsByLimitId")]
        public System.Collections.Generic.IDictionary<string, RateLimitBucket> RateLimitsByLimitId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RateLimitBucket
    {

        [System.Text.Json.Serialization.JsonPropertyName("limitId")]
        public string LimitId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limitName")]
        public string LimitName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("primary")]
        public RateLimitWindow Primary { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("secondary")]
        public RateLimitWindow Secondary { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RateLimitWindow
    {

        [System.Text.Json.Serialization.JsonPropertyName("usedPercent")]
        public int? UsedPercent { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windowDurationMins")]
        public int? WindowDurationMins { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("resetsAt")]
        public long? ResetsAt { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ModelListResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Collections.Generic.ICollection<ModelInfo> Data { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nextCursor")]
        public string NextCursor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ModelInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("model")]
        public string Model { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        public string DisplayName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hidden")]
        public bool Hidden { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("defaultReasoningEffort")]
        public string DefaultReasoningEffort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("supportedReasoningEfforts")]
        public System.Collections.Generic.ICollection<ReasoningEffortInfo> SupportedReasoningEfforts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("inputModalities")]
        public System.Collections.Generic.ICollection<string> InputModalities { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("supportsPersonality")]
        public bool SupportsPersonality { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isDefault")]
        public bool IsDefault { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ReasoningEffortInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("reasoningEffort")]
        public string ReasoningEffort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadListResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Collections.Generic.ICollection<ThreadSummary> Data { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nextCursor")]
        public string NextCursor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadReadResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("thread")]
        public ThreadDetail Thread { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadStartResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("thread")]
        public ThreadDetail Thread { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("model")]
        public string Model { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("modelProvider")]
        public string ModelProvider { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnStartResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("turn")]
        public ThreadTurn Turn { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnInterruptResult
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadSummary
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("preview")]
        public string Preview { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ephemeral")]
        public bool Ephemeral { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("modelProvider")]
        public string ModelProvider { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        public long? CreatedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
        public long? UpdatedAt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public ThreadStatusInfo Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cwd")]
        public string Cwd { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadDetail : ThreadSummary
    {

        [System.Text.Json.Serialization.JsonPropertyName("turns")]
        public System.Collections.Generic.ICollection<ThreadTurn> Turns { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadStatusInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("activeFlags")]
        public System.Collections.Generic.ICollection<string> ActiveFlags { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadTurn
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.ICollection<ThreadItem> Items { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("error")]
        public ThreadTurnError Error { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadTurnError
    {

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("additionalDetails")]
        public string AdditionalDetails { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("phase")]
        public string Phase { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public System.Text.Json.JsonElement Content { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("summary")]
        public System.Text.Json.JsonElement Summary { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("command")]
        public string Command { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cwd")]
        public string Cwd { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("processId")]
        public string ProcessId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("commandActions")]
        public System.Text.Json.JsonElement CommandActions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("aggregatedOutput")]
        public string AggregatedOutput { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("exitCode")]
        public int? ExitCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("durationMs")]
        public long? DurationMs { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("changes")]
        public System.Collections.Generic.ICollection<FileUpdateChange> Changes { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("server")]
        public string Server { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tool")]
        public string Tool { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("arguments")]
        public System.Text.Json.JsonElement Arguments { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public McpToolCallResult Result { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("error")]
        public McpToolCallError Error { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("contentItems")]
        public System.Collections.Generic.ICollection<DynamicToolCallOutputContentItem> ContentItems { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("senderThreadId")]
        public string SenderThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("receiverThreadIds")]
        public System.Collections.Generic.ICollection<string> ReceiverThreadIds { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("prompt")]
        public string Prompt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("model")]
        public string Model { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("reasoningEffort")]
        public string ReasoningEffort { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("agentsStates")]
        public System.Collections.Generic.IDictionary<string, CollabAgentState> AgentsStates { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileUpdateChange
    {

        [System.Text.Json.Serialization.JsonPropertyName("path")]
        public string Path { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("kind")]
        public string Kind { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("diff")]
        public string Diff { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class McpToolCallResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public System.Collections.Generic.ICollection<System.Text.Json.JsonElement> Content { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("structuredContent")]
        public System.Text.Json.JsonElement StructuredContent { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class McpToolCallError
    {

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DynamicToolCallOutputContentItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("imageUrl")]
        public string ImageUrl { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollabAgentState
    {

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserInputItem
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("path")]
        public string Path { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnStartedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turn")]
        public ThreadTurn Turn { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadStartedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("thread")]
        public ThreadSummary Thread { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadStatusChangedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public ThreadStatusInfo Status { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ThreadNameUpdatedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("threadName")]
        public string ThreadName { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnCompletedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turn")]
        public ThreadTurn Turn { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ItemLifecycleNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("item")]
        public ThreadItem Item { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AgentMessageDeltaNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("delta")]
        public string Delta { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PlanDeltaNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("delta")]
        public string Delta { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommandExecutionOutputDeltaNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("delta")]
        public string Delta { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TerminalInteractionNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("processId")]
        public string ProcessId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("stdin")]
        public string Stdin { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileChangeOutputDeltaNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("delta")]
        public string Delta { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class McpToolCallProgressNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnDiffUpdatedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("diff")]
        public string Diff { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnPlanUpdatedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("explanation")]
        public string Explanation { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("plan")]
        public System.Collections.Generic.ICollection<TurnPlanStep> Plan { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TurnPlanStep
    {

        [System.Text.Json.Serialization.JsonPropertyName("step")]
        public string Step { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string Status { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ServerRequestResolvedNotification
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("requestId")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Text.Json.JsonElement RequestId { get; set; } = new System.Text.Json.JsonElement();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CommandExecutionRequestApprovalParams
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("approvalId")]
        public string ApprovalId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string Reason { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("command")]
        public string Command { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cwd")]
        public string Cwd { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("commandActions")]
        public System.Text.Json.JsonElement CommandActions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("networkApprovalContext")]
        public NetworkApprovalContext NetworkApprovalContext { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("proposedExecpolicyAmendment")]
        public System.Collections.Generic.ICollection<string> ProposedExecpolicyAmendment { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("proposedNetworkPolicyAmendments")]
        public System.Collections.Generic.ICollection<NetworkPolicyAmendment> ProposedNetworkPolicyAmendments { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("additionalPermissions")]
        public System.Text.Json.JsonElement AdditionalPermissions { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("skillMetadata")]
        public System.Text.Json.JsonElement SkillMetadata { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("availableDecisions")]
        public System.Text.Json.JsonElement AvailableDecisions { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NetworkApprovalContext
    {

        [System.Text.Json.Serialization.JsonPropertyName("host")]
        public string Host { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("protocol")]
        public string Protocol { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("port")]
        public int? Port { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NetworkPolicyAmendment
    {

        [System.Text.Json.Serialization.JsonPropertyName("action")]
        public string Action { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("host")]
        public string Host { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileChangeRequestApprovalParams
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string Reason { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("grantRoot")]
        public string GrantRoot { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DynamicToolCallParams
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("callId")]
        public string CallId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tool")]
        public string Tool { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("arguments")]
        public System.Text.Json.JsonElement Arguments { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ToolRequestUserInputParams
    {

        [System.Text.Json.Serialization.JsonPropertyName("threadId")]
        public string ThreadId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("turnId")]
        public string TurnId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("itemId")]
        public string ItemId { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("questions")]
        public System.Collections.Generic.ICollection<ToolRequestUserInputQuestion> Questions { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ToolRequestUserInputQuestion
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("header")]
        public string Header { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("question")]
        public string Question { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isOther")]
        public bool IsOther { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isSecret")]
        public bool IsSecret { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("options")]
        public System.Collections.Generic.ICollection<ToolRequestUserInputOption> Options { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ToolRequestUserInputOption
    {

        [System.Text.Json.Serialization.JsonPropertyName("label")]
        public string Label { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppListResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Collections.Generic.ICollection<AppInfo> Data { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nextCursor")]
        public string NextCursor { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AppInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("installUrl")]
        public string InstallUrl { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isAccessible")]
        public bool IsAccessible { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("logoUrl")]
        public string LogoUrl { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkillsListResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Collections.Generic.ICollection<SkillsByWorkingDirectory> Data { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkillsByWorkingDirectory
    {

        [System.Text.Json.Serialization.JsonPropertyName("cwd")]
        public string Cwd { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("skills")]
        public System.Collections.Generic.ICollection<SkillInfo> Skills { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("errors")]
        public System.Collections.Generic.ICollection<string> Errors { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkillInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("interface")]
        public SkillInterfaceInfo Interface { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SkillInterfaceInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("displayName")]
        public string DisplayName { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("shortDescription")]
        public string ShortDescription { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConfigRequirementsReadResult
    {

        [System.Text.Json.Serialization.JsonPropertyName("requirements")]
        public ConfigRequirementsInfo Requirements { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ConfigRequirementsInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("allowedApprovalPolicies")]
        public System.Collections.Generic.ICollection<string> AllowedApprovalPolicies { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("allowedSandboxModes")]
        public System.Collections.Generic.ICollection<string> AllowedSandboxModes { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("featureRequirements")]
        public System.Collections.Generic.IDictionary<string, bool> FeatureRequirements { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("network")]
        public NetworkRequirementsInfo Network { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class NetworkRequirementsInfo
    {

        [System.Text.Json.Serialization.JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("allowedDomains")]
        public System.Collections.Generic.ICollection<string> AllowedDomains { get; set; }

    }



}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625